### ISSUE TITLE
[Igor] Error: Call to undefined function sexplode()

### ISSUE THREAD

**Issue by fiwswe** [cosmocode/dokuwiki-plugin-doi#1]
When using the `[[doi>…]]` syntax on Igor:
`Error: Call to undefined function sexplode() /var/www/dokuwiki/lib/plugins/doi/syntax/doi.php(43)`

Note: `[[isbn>…]]` works fine.

I have marked the [plugin](https://www.dokuwiki.org/plugin%3Adoi) as incompatible with Igor for now.

Hogfather and older are also affected AFAICT.

DokuWiki version: Release 2022-07-31b "Igor", PHP 8.2.8

**Comment by splitbrain** [comment]
correct. sexplode was introduced in jack jackrum
