### ISSUE TITLE
Icon fills background behind title, making it hard to read

### ISSUE THREAD

**Issue by SECtim** [cosmocode/dokuwiki-plugin-doi#3]
First of all, thank you for this plugin!

The following style...
https://github.com/cosmocode/dokuwiki-plugin-doi/blob/a4d2e0b133770aa7f48623659f25870222a67a5c/style.less#L5-L7
... leads to this output:
![image](https://github.com/cosmocode/dokuwiki-plugin-doi/assets/42440411/2895ad63-6d7c-44b8-86f4-d84f054b86bf)

With `background-repeat: no-repeat;`, I still get
![image](https://github.com/cosmocode/dokuwiki-plugin-doi/assets/42440411/1258d349-065f-4535-8152-0e31bbb7d0a2)

For now, I will just remove the background completely on my Dokuwiki instance. However, I am not very knowledgeable in CSS, so there might be an easy solution I am not aware of.

Maybe relevant: I am using Firefox 118.0.2. I am of course happy to provide additional information if needed.

**Comment by splitbrain** [comment]
Which template are you using?

**Comment by SECtim** [comment]
Thanks! Just to answer your original question: the template is some custom template created by the previous maintainer of this particular Dokuwiki instance.
